require:
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'Rakefile'
    - 'config.ru'
  NewCops: enable

Style/Documentation:
  Enabled: false
RSpec/ContextWording:
  AllowedPatterns:
    - 場合$
RSpec/MultipleExpectations:
  Enabled: true
  Max: 3
RSpec/IndexedLet:
  Enabled: false
