services:
  web:
    build:
      context: "."
    environment:
      - TEST_MYSQL_DATABASE_URL=mysql://root:root@test_mysql:3306/test
      - TEST_POSTGRESQL_DATABASE_URL=postgresql://postgres:postgres@test_postgresql:5432/test
    depends_on:
      test_postgresql:
        condition: service_started
      test_mysql:
        condition: service_healthy
  test_postgresql:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
  test_mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
